import type { Metadata } from 'next';
import localFont from 'next/font/local';
import Navbar from '@/components/Navbar';
import './globals.css';
import Footer from '@/components/Footer';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} 
      antialiased bg-black mx-[24px] text-white`}
      >
        {/* navbar */}
        <nav className="py-[16px]">
          <Navbar />
        </nav>
        {/* mane section */}
        <main>{children}</main>
        {/*footer  */}
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
